// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugyldpmninyakvgrvvju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVneWxkcG1uaW55YWt2Z3J2dmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjA4MDUsImV4cCI6MjA2NjQzNjgwNX0._rzjccp6rx4W0aeE4lyef-veFmGP7eX876h5PBvLUUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);